version: "2"
linters:
  default: "all"
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/codyonesock
            - github.com/go-chi
            - go.uber.org/zap
            - github.com/kelseyhightower/envconfig
    exhaustruct:
      exclude:
        - '^net/http\.Server$'
        - '^go\.uber\.org/zap\.Config$'
    tagliatelle:
      case:
        rules:
          json: snake
    varnamelen:
      min-name-length: 1
  disable:
    - nlreturn
    - tagalign